"""PDF report generator for MailGuard AI security reports."""

from fpdf import FPDF
from datetime import datetime


class SecurityReportPDF(FPDF):
    """Custom PDF class for security reports."""
    
    def header(self):
        self.set_font('Helvetica', 'B', 20)
        self.set_text_color(41, 128, 185)  # Blue
        self.cell(0, 15, 'MailGuard AI', ln=True, align='C')
        self.set_font('Helvetica', '', 10)
        self.set_text_color(127, 140, 141)  # Gray
        self.cell(0, 8, 'Email Security Analysis & Threat Forensics Report', ln=True, align='C')
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(8)
    
    def footer(self):
        self.set_y(-20)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(127, 140, 141)
        self.cell(0, 10, f'Generated by MailGuard AI | {datetime.now().strftime("%Y-%m-%d %H:%M")}', align='C')
        self.ln(4)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', align='C')
    
    def section_title(self, title: str):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(44, 62, 80)  # Dark blue
        self.cell(0, 10, title, ln=True)
        self.ln(2)
    
    def section_body(self, text: str):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(52, 73, 94)
        self.multi_cell(0, 6, text)
        self.ln(4)
    
    def risk_badge(self, risk_level: str, risk_score: int):
        colors = {
            'LOW': (46, 204, 113),
            'MEDIUM': (241, 196, 15),
            'HIGH': (230, 126, 34),
            'CRITICAL': (231, 76, 60)
        }
        r, g, b = colors.get(risk_level, (149, 165, 166))
        
        self.set_fill_color(r, g, b)
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 16)
        
        badge_text = f'  RISK: {risk_level} ({risk_score}/100)  '
        w = self.get_string_width(badge_text) + 12
        x = (210 - w) / 2
        self.set_x(x)
        self.cell(w, 14, badge_text, fill=True, ln=True, align='C')
        self.ln(8)
        self.set_text_color(0, 0, 0)


def generate_pdf_report(report_data: dict) -> bytes:
    """Generate a PDF security report.
    
    Args:
        report_data: Complete report data dictionary containing:
            - ml_result, url_analysis, keyword_analysis,
            - pattern_analysis, header_analysis, vt_analysis, risk_result, report_text
    
    Returns:
        PDF file as bytes
    """
    pdf = SecurityReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    ml_result = report_data.get('ml_result', {})
    risk_result = report_data.get('risk_result', {})
    header_analysis = report_data.get('header_analysis', {})
    vt_analysis = report_data.get('vt_analysis', {})
    
    # Classification Summary
    prediction = ml_result.get('prediction', 'unknown').upper()
    spam_prob = ml_result.get('spam_probability', 0)
    
    pdf.section_title('Classification Summary')
    pdf.set_font('Helvetica', 'B', 24)
    if prediction == 'SPAM':
        pdf.set_text_color(231, 76, 60)
    else:
        pdf.set_text_color(46, 204, 113)
    pdf.cell(0, 15, prediction, ln=True, align='C')
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Helvetica', '', 11)
    pdf.cell(0, 8, f'Spam Probability: {spam_prob:.2%}   |   Ham Probability: {ml_result.get("ham_probability", 0):.2%}', ln=True, align='C')
    pdf.ln(6)
    
    # Risk Badge
    risk_level = risk_result.get('risk_level', 'UNKNOWN')
    risk_score = risk_result.get('risk_score', 0)
    pdf.risk_badge(risk_level, risk_score)

    # VirusTotal URL Threat Intelligence Section
    if vt_analysis and vt_analysis.get('results'):
        pdf.section_title('VirusTotal URL Security Analysis')
        for res in vt_analysis['results']:
            url = res.get('url', '')
            status = res.get('classification', res.get('status', ''))
            mal = res.get('malicious', 0)
            susp = res.get('suspicious', 0)
            
            # Sanitize for latin-1
            safe_url = url.encode('latin-1', errors='replace').decode('latin-1')
            safe_status = status.encode('latin-1', errors='replace').decode('latin-1')
            
            pdf.set_font('Helvetica', 'B', 10)
            pdf.set_text_color(44, 62, 80)
            pdf.cell(0, 6, f"URL: {safe_url[:70]}...", ln=True)
            
            pdf.set_font('Helvetica', '', 9)
            if mal > 0:
                pdf.set_text_color(231, 76, 60)
                pdf.cell(0, 5, f"  Status: Malicious ({mal} security engines flagged, {susp} suspicious)", ln=True)
            elif susp > 0:
                pdf.set_text_color(230, 126, 34)
                pdf.cell(0, 5, f"  Status: Suspicious ({susp} engines flagged)", ln=True)
            else:
                pdf.set_text_color(46, 204, 113)
                pdf.cell(0, 5, f"  Status: No malicious detections reported by VirusTotal", ln=True)
        pdf.ln(4)

    # Header Security Section (if present)
    if header_analysis and header_analysis.get('has_headers', False):
        pdf.section_title('Email Header Authentication & Forensics')
        auth = header_analysis.get('auth_results', {})
        sender = header_analysis.get('sender_info', {})
        
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(52, 73, 94)
        pdf.cell(0, 6, f"From: {sender.get('from_email', 'N/A')}  |  Return-Path: {sender.get('return_path', 'N/A')}", ln=True)
        pdf.cell(0, 6, f"SPF: {auth.get('spf', 'NONE')}  |  DKIM: {auth.get('dkim', 'NONE')}  |  DMARC: {auth.get('dmarc', 'NONE')}", ln=True)
        
        if header_analysis.get('spoofing_detected'):
            pdf.set_text_color(231, 76, 60)
            pdf.set_font('Helvetica', 'B', 10)
            pdf.cell(0, 6, "WARNING: Sender Domain Spoofing Detected!", ln=True)
            pdf.set_text_color(52, 73, 94)
            pdf.set_font('Helvetica', '', 10)
            
        pdf.ln(4)
    
    # Full Report Text
    report_text = report_data.get('report_text', '')
    if report_text:
        safe_text = report_text.encode('latin-1', errors='replace').decode('latin-1')
        pdf.section_body(safe_text)
    
    # Contributing Factors
    factors = risk_result.get('contributing_factors', [])
    if factors:
        pdf.section_title('Risk Contributing Factors')
        for f in factors:
            pdf.set_font('Helvetica', '', 10)
            pdf.set_text_color(52, 73, 94)
            safe_factor = f"{f['factor']}: +{f['points']} pts - {f['description']}".encode('latin-1', errors='replace').decode('latin-1')
            pdf.cell(0, 7, f"  - {safe_factor}", ln=True)
        pdf.ln(4)
    
    # Disclaimer
    pdf.ln(8)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(149, 165, 166)
    pdf.multi_cell(0, 5, 
        'Disclaimer: This report is generated by an automated security system and should be used '
        'as a guide. Always exercise caution with suspicious emails. MailGuard AI does not guarantee 100% detection.'
    )
    
    return bytes(pdf.output())
